### ISSUE TITLE
Как использовать этот hook с набором инструментов v140_xp ?

### ISSUE THREAD

**Issue by Tim4ukys** [imring/RakHook#1]
При компиляции с данным набором инструментов компилятор выдаёт в это
![image](https://user-images.githubusercontent.com/73384372/115594703-3e91c480-a300-11eb-8db4-306e8bbe9c7c.png)
Сильно не шарю за С\С++, да и гугл мне не сильно помог с решением данной проблемы, так что надеюсь на вашу помощь. 

Я знаю что под v141_xp норм компилируется, но мне _**нужно именно v140_xp**_, т.к. потом будет меньше мороки с конечным пользователем. **_Заранее спасибо за помощь!_**

**Comment by imring** [comment]
Привет.
Измени стандарт языка C++ в своем проекте на C++17 или C++latest:
![изображение](https://user-images.githubusercontent.com/35897995/115601193-2b71fb00-a2e6-11eb-8786-f3fee12b3e8b.png)

**Comment by Tim4ukys** [comment]
> Привет.
> Измени стандарт языка C++ в своем проекте на C++17 или C++latest:
> ![изображение](https://user-images.githubusercontent.com/35897995/115601193-2b71fb00-a2e6-11eb-8786-f3fee12b3e8b.png)

Было бы всё так просто 😢
![image](https://user-images.githubusercontent.com/73384372/115652329-42046a80-a357-11eb-99de-3459eab0ff39.png)
Если выбрать набор инструментов **_v140_xp_**, то выбор стандарта языка вообще куда-то испаряется😐
Блуждая по интернету я понял только то, что inline можно не задумываясь просто убрать и на одну "error" станет меньше

Я понимаю, что можно использовать набор инструментов v141_xp, там как раз появляется выбор стандарта языка C++ (14, 17 и latest), но камон, хотелось бы использовать именно v140_xp

**Comment by Tim4ukys** [comment]
Проблема высосанная из пальца. inline можно просто удалять и приписать const, где-то можно без auto обойтись, а где-то constexpr превратить в void и прописать в #define, но подводные камни всё же попадались, да и такие, которые хз как обойти. 
Но из всех хуков raknet`а, это ед. такой, так что придётся переходить под v141_xp и менять стандарт языка на 17.

Если хочешь, то переписывай под C++14, идею можно сказать я тебе подкинул.
